

services:
  redis:
    image: valkey/valkey
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 60s
        order: start-first
        failure_action: rollback
        monitor: 60s
      rollback_config:
        parallelism: 1
        delay: 10s
        order: stop-first
    networks:
      - nw
  
  postgres:
    image: postgres:17-alpine 
    env_file:
      - .env
    environment:
      PGDATA: /var/lib/postgresql/db
      POSTGRES_DB: glitchtip-db
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 30s
        order: start-first
        failure_action: rollback
        monitor: 30s
      rollback_config:
        parallelism: 1
        delay: 10s 
        order: stop-first
    networks:
      - nw 
    volumes: 
      - /mnt/glusterfs/glitchtip/postgres/db:/var/lib/postgresql/db
  
  web:
    image: glitchtip/glitchtip:v4.1
    env_file:
      - .env
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 60s
        order: start-first
        failure_action: rollback
        monitor: 60s
      rollback_config:
        parallelism: 1
        delay: 10s
        order: stop-first
    networks:
      - nw
    ports:
      - "48000:8000"
    volumes: 
      - /mnt/glusterfs/glitchtip/code/uploads:/code/uploads

  worker:
    image: glitchtip/glitchtip:v4.1
    env_file:
      - .env
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 60s
        order: start-first
        failure_action: rollback
        monitor: 60s
      rollback_config:
        parallelism: 1
        delay: 10s
        order: stop-first
    networks:
      - nw
    command: ./bin/run-celery-with-beat.sh
    volumes: 
      - /mnt/glusterfs/glitchtip/code/uploads:/code/uploads

  migrate:
    image: glitchtip/glitchtip:v4.1
    env_file:
      - .env
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 60s
        order: start-first
        failure_action: rollback
        monitor: 60s
      rollback_config:
        parallelism: 1
        delay: 10s
        order: stop-first
    networks:
      - nw
    command: ./bin/run-migrate.sh

networks:
  nw:
    driver: overlay
