

services:
  redis:
    image: valkey/valkey
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 60s
        order: start-first
        failure_action: rollback
        monitor: 60s
      rollback_config:
        parallelism: 1
        delay: 10s
        order: stop-first
    networks:
      - nw

  web:
    image: glitchtip/glitchtip
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 60s
        order: start-first
        failure_action: rollback
        monitor: 60s
      rollback_config:
        parallelism: 1
        delay: 10s
        order: stop-first
    networks:
      - nw
    ports:
      - "48000:8000"
    volumes: 
      - /mnt/glusterfs/glitchtip/code/uploads:/code/uploads

  worker:
    image: glitchtip/glitchtip
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 60s
        order: start-first
        failure_action: rollback
        monitor: 60s
      rollback_config:
        parallelism: 1
        delay: 10s
        order: stop-first
    networks:
      - nw
    command: ./bin/run-celery-with-beat.sh
    volumes: 
      - /mnt/glusterfs/glitchtip/code/uploads:/code/uploads

  migrate:
    image: glitchtip/glitchtip
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 60s
        order: start-first
        failure_action: rollback
        monitor: 60s
      rollback_config:
        parallelism: 1
        delay: 10s
        order: stop-first
    networks:
      - nw
    command: ./bin/run-migrate.sh

networks:
  nw:
    driver: overlay
